# Generated by Django 3.2 on 2021-06-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartApp', '0003_alter_cartitem_shipping_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='shipping_fee',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
