# Generated by Django 3.2 on 2021-06-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartApp', '0004_alter_cartitem_shipping_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_shipping_fee',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='shipping_fee',
            field=models.IntegerField(null=True),
        ),
    ]
