# Generated by Django 3.2 on 2021-06-03 20:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnail/')),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('stock', models.IntegerField()),
                ('salesamount', models.IntegerField()),
                ('category', models.CharField(choices=[('rings', 'rings'), ('glasses', 'glasses'), ('hats', 'hats'), ('necklace', 'necklace')], max_length=20)),
                ('pubDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('published', models.BooleanField(default=True)),
                ('shipping_fee', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'under 10000'), (1, '10000-19990'), (2, '20000-29990'), (3, '30000-39990'), (4, '40000-49990'), (5, 'up to 50000')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_stage', models.CharField(choices=[('적극추천', '적극추천'), ('추천', '추천'), ('비추천', '비추천')], default='', max_length=20)),
                ('shipping_score', models.CharField(choices=[('빠름', '빠름'), ('보통', '보통'), ('느림', '느림')], default='', max_length=20)),
                ('r_content', models.TextField(null=True)),
                ('total_score', models.CharField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], default='', max_length=20)),
                ('pubDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('r_user_id', models.CharField(max_length=50)),
                ('product_num', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productApp.product')),
            ],
        ),
    ]
