# Generated by Django 3.2 on 2021-05-13 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_range',
            field=models.CharField(choices=[('10000-19990', '10000-19990'), ('upper 50000', 'upper 50000'), ('40000-49990', '40000-49990'), ('20000-29990', '20000-29990'), ('30000-39990', '30000-39990'), ('under 10000', 'under 10000')], max_length=30, null=True),
        ),
    ]
