# Generated by Django 3.2 on 2021-06-03 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='product_num',
            new_name='product',
        ),
    ]
