# Generated by Django 3.2 on 2021-06-03 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0002_rename_product_num_review_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='product',
            new_name='product_num',
        ),
    ]
