# Generated by Django 3.2 on 2021-05-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0003_auto_20210513_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('rings', 'rings'), ('sunglasses', 'sunglasses'), ('socks', 'socks')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
