# Generated by Django 3.2 on 2021-06-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0003_rename_product_review_product_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='total_score',
            field=models.IntegerField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], default='', max_length=20),
        ),
    ]
