# Generated by Django 3.2.2 on 2021-05-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0004_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('rings', 'rings'), ('glasses', 'glasses'), ('socks', 'socks'), ('necklace', 'necklace')], max_length=20),
        ),
    ]
