# Generated by Django 3.2 on 2021-06-03 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0006_alter_review_total_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='product_num',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='productApp.product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='r_content',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='r_user_id',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
