# Generated by Django 3.2.2 on 2021-05-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0006_auto_20210514_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('rings', 'rings'), ('glasses', 'glasses'), ('socks', 'socks'), ('necklace', 'necklace'), ('hats', 'hats')], max_length=20),
        ),
    ]
