# Generated by Django 3.2.2 on 2021-05-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('rings', 'rings'), ('glasses', 'glasses'), ('hats', 'hats'), ('necklace', 'necklace')], max_length=20),
        ),
    ]
