# Generated by Django 3.2 on 2021-06-03 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0007_auto_20210604_0550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='product_num',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='review',
            name='pubDate',
        ),
    ]
