# Generated by Django 3.2 on 2021-06-03 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0008_auto_20210604_0551'),
    ]

    operations = [
        migrations.DeleteModel(
            name='review',
        ),
    ]
