# Generated by Django 3.2 on 2021-06-03 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0009_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_stage', models.CharField(choices=[('적극추천', '적극추천'), ('추천', '추천'), ('비추천', '비추천')], default='', max_length=20)),
                ('shipping_score', models.CharField(choices=[('빠름', '빠름'), ('보통', '보통'), ('느림', '느림')], default='', max_length=20)),
                ('r_content', models.TextField(default='', null=True)),
                ('total_score', models.IntegerField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], default='')),
                ('r_user_id', models.CharField(default='', max_length=50, null=True)),
                ('product', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='productApp.product')),
            ],
        ),
    ]
