# Generated by Django 3.2 on 2021-06-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0010_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='r_content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='r_user_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
