# Generated by Django 3.2.2 on 2021-05-22 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0010_auto_20210519_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='status',
        ),
    ]
