# Generated by Django 3.2 on 2021-06-03 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0011_auto_20210604_0606'),
    ]

    operations = [
        migrations.DeleteModel(
            name='review',
        ),
    ]
