# Generated by Django 3.2 on 2021-06-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0013_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='total_score',
            field=models.CharField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], max_length=5),
        ),
    ]
