# Generated by Django 3.2.2 on 2021-05-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0013_auto_20210525_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.IntegerField(choices=[(0, 'under 10000'), (1, '10000-19990'), (2, '20000-29990'), (3, '30000-39990'), (4, '40000-49990'), (5, 'up to 50000')], default=0),
        ),
    ]
