# Generated by Django 3.2 on 2021-06-03 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0014_alter_review_total_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='product',
            new_name='r_product',
        ),
    ]
