# Generated by Django 3.2 on 2021-06-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0014_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_fee',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
