# Generated by Django 3.2 on 2021-06-04 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0015_rename_product_review_r_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='pubDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
