# Generated by Django 3.2 on 2021-06-04 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0016_review_pubdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='pubDate',
        ),
    ]
