# Generated by Django 3.2 on 2021-06-07 06:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0018_alter_review_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
