# Generated by Django 3.2 on 2021-06-07 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0020_product_avg_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='avg_score',
        ),
    ]
