# Generated by Django 3.2 on 2021-05-31 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0003_orderitem_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Order_id',
            new_name='order_id',
        ),
    ]
