# Generated by Django 3.2 on 2021-06-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0003_order_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='before_discount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
