# Generated by Django 3.2 on 2021-05-31 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0004_rename_order_id_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
