# Generated by Django 3.2 on 2021-05-31 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0005_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
