# Generated by Django 3.2 on 2021-05-31 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0006_order_total_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_state',
            field=models.CharField(choices=[('pay_continue', 'pay_continue'), ('order_cancle', 'order_cancle'), ('pay_cancle', 'pay_cancle'), ('pay_complete', 'pay_complete'), ('shipping', 'shipping'), ('shipping_complete', 'shipping_complete'), ('order_complete', 'order_complete')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
