# Generated by Django 3.2 on 2021-05-31 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0007_order_order_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_user',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
