# Generated by Django 3.2 on 2021-05-31 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0008_order_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_state',
            field=models.CharField(choices=[('order_continue', 'order_continue'), ('order_cancle', 'order_cancle'), ('pay_cancle', 'pay_cancle'), ('pay_complete', 'pay_complete'), ('shipping', 'shipping'), ('shipping_complete', 'shipping_complete'), ('order_complete', 'order_complete')], max_length=20),
        ),
    ]
