# Generated by Django 3.2 on 2021-05-31 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0009_alter_order_order_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
    ]
