# Generated by Django 3.2 on 2021-06-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0010_remove_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_title',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
