# Generated by Django 3.2 on 2021-06-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0011_orderitem_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
