# Generated by Django 3.2 on 2021-06-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0012_order_shipping_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_fee',
            new_name='total_shipping_fee',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shipping_fee',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
