# Generated by Django 3.2 on 2021-06-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0013_auto_20210601_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
