# Generated by Django 3.2 on 2021-06-01 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0015_order_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pub_date',
            new_name='pubDate',
        ),
    ]
