# Generated by Django 3.2 on 2021-06-01 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0016_rename_pub_date_order_pubdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pubDate',
        ),
    ]
