# Generated by Django 3.2 on 2021-06-08 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice_Event',
            fields=[
                ('noti_event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('pubdate', models.DateTimeField(auto_now_add=True)),
                ('contents', models.TextField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='notice/')),
                ('on_off', models.BooleanField()),
                ('dueDate', models.DateTimeField()),
            ],
        ),
    ]
