# Generated by Django 3.2 on 2021-05-13 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('contents', models.TextField()),
                ('activation', models.CharField(choices=[('off', 'Off')], max_length=10)),
                ('dueDate', models.DateTimeField()),
                ('uniqueNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('contents', models.TextField()),
                ('uniqueNumber', models.IntegerField()),
            ],
        ),
    ]
