# Generated by Django 3.2 on 2021-05-13 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='uniqueNumber',
            new_name='EventId',
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='uniqueNumber',
            new_name='noticeId',
        ),
    ]
