# Generated by Django 3.2 on 2021-05-13 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticeApp', '0002_auto_20210513_0122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='EventId',
            new_name='eventId',
        ),
    ]
