# Generated by Django 3.2 on 2021-05-13 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeApp', '0003_rename_eventid_event_eventid'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='on_off',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='activation',
            field=models.CharField(max_length=10),
        ),
    ]
