# Generated by Django 3.2 on 2021-05-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeApp', '0004_auto_20210513_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice_Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noti_event_id', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('pubdate', models.DateTimeField(auto_now_add=True)),
                ('contents', models.TextField()),
                ('on_off', models.BooleanField()),
                ('activation', models.CharField(max_length=10)),
                ('dueDate', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
