# Generated by Django 3.2 on 2021-05-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeApp', '0005_auto_20210516_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice_event',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
