# Generated by Django 3.2 on 2021-05-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeApp', '0006_notice_event_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice_event',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='notice/'),
        ),
    ]
