# Generated by Django 3.2 on 2021-05-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeApp', '0007_alter_notice_event_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice_event',
            name='id',
        ),
        migrations.AlterField(
            model_name='notice_event',
            name='noti_event_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
