# Generated by Django 3.2 on 2021-05-30 17:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(null=True)),
                ('pubDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_checked', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
