# Generated by Django 3.2 on 2021-06-03 18:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(null=True)),
                ('q_category', models.CharField(choices=[('상품', '상품'), ('배송', '배송'), ('반품/취소', '반품/취소'), ('기타', '기타')], max_length=20, null=True)),
                ('pubDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_checked', models.BooleanField(default=False, null=True)),
                ('q_user_id', models.CharField(max_length=50)),
            ],
        ),
    ]
