# Generated by Django 3.2 on 2021-06-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='q_category',
            field=models.CharField(choices=[('상품', '상품'), ('배송', '배송'), ('반품/취소', '반품/취소'), ('기타', '기타')], default='', max_length=20),
        ),
    ]
