# Generated by Django 3.2 on 2021-06-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionApp', '0002_alter_question_q_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='product_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
