# Generated by Django 3.2 on 2021-06-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionApp', '0003_auto_20210606_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='product_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
