# Generated by Django 3.2 on 2021-04-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('user_pw', models.CharField(max_length=100)),
                ('user_address', models.TextField()),
                ('user_email', models.CharField(max_length=100)),
                ('user_phone', models.IntegerField(null=True)),
            ],
        ),
    ]
