# Generated by Django 3.2 on 2021-06-07 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('user_pw', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=20)),
                ('user_email', models.CharField(max_length=100)),
                ('user_phone', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('post_num', models.CharField(max_length=200, null=True)),
                ('road_address', models.CharField(max_length=200, null=True)),
                ('detail_address', models.TextField()),
                ('post_name', models.CharField(max_length=20, null=True)),
                ('post_phonenum', models.IntegerField(null=True)),
                ('is_default', models.BooleanField(default=False, null=True)),
                ('accounts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingApp.useraccounts')),
            ],
        ),
    ]
