# Generated by Django 3.2 on 2021-04-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccounts',
            name='user_phone',
            field=models.IntegerField(null=True),
        ),
    ]
