# Generated by Django 3.2 on 2021-05-04 01:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingApp', '0003_event_notice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='createDate',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='createDate',
        ),
        migrations.AddField(
            model_name='event',
            name='cdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notice',
            name='cdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
