# Generated by Django 3.2.2 on 2021-05-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingApp', '0005_alter_useraccounts_user_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='iteminfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('item_name', models.CharField(max_length=50)),
                ('item_price', models.IntegerField()),
                ('item_description', models.TextField()),
                ('item_amount', models.IntegerField()),
                ('item_sales', models.IntegerField()),
            ],
        ),
    ]
