# Generated by Django 3.2.2 on 2021-05-12 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingApp', '0007_auto_20210512_0348'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
    ]
