# Generated by Django 3.2 on 2021-05-13 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingApp', '0008_delete_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
