# Generated by Django 3.2.2 on 2021-05-19 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingApp', '0010_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user_name',
        ),
        migrations.AddField(
            model_name='address',
            name='UserAccounts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingApp.useraccounts'),
        ),
    ]
