# Generated by Django 3.2.2 on 2021-05-22 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingApp', '0011_auto_20210520_0059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='UserAccounts',
            new_name='accounts',
        ),
    ]
