# Generated by Django 3.2.2 on 2021-05-22 18:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingApp', '0012_rename_useraccounts_address_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
