# Generated by Django 3.2 on 2021-05-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingApp', '0013_address_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='body',
        ),
        migrations.RemoveField(
            model_name='address',
            name='title',
        ),
        migrations.AddField(
            model_name='address',
            name='doro',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='jibun',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='post_address',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='sum_ad',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
