# Generated by Django 3.2 on 2021-05-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingApp', '0014_auto_20210523_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='doro',
        ),
        migrations.RemoveField(
            model_name='address',
            name='jibun',
        ),
        migrations.RemoveField(
            model_name='address',
            name='post_address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='sum_ad',
        ),
        migrations.AddField(
            model_name='address',
            name='body',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
