# Generated by Django 3.2.2 on 2021-05-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingApp', '0015_auto_20210523_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='body',
            new_name='detail_address',
        ),
        migrations.AddField(
            model_name='address',
            name='post_num',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='road_address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
