# Generated by Django 3.2.2 on 2021-05-24 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingApp', '0016_auto_20210524_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='pub_date',
        ),
    ]
