# Generated by Django 3.2.2 on 2021-05-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingApp', '0017_remove_address_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='post_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='post_phonenum',
            field=models.IntegerField(null=True),
        ),
    ]
