# Generated by Django 3.2 on 2021-06-05 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couponApp', '0002_auto_20210605_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='price',
        ),
    ]
