# Generated by Django 3.2 on 2021-06-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couponApp', '0003_remove_coupon_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='before_discount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
